### ISSUE TITLE
Need reference links

### ISSUE THREAD

**Issue by dvigneshwer** [dougsouza/face-frontalization#1]
Can share reference links for camera_calibration (calib_camera function ) and frontalize ( frontalize function) scripts?

**Comment by dougsouza** [comment]
What do you mean by reference links? The work where those functions came from? If yes:
Camera calibration: [http://www.openu.ac.il/home/hassner/projects/poses/](http://www.openu.ac.il/home/hassner/projects/poses/)
Frontalization: [http://www.openu.ac.il/home/hassner/projects/frontalize/](http://www.openu.ac.il/home/hassner/projects/frontalize/)

Otherwise, if you mean reference as documentation, we don't have any docs. The code is pretty straightforward though, you can take a look and see how it works.

Have I answered your question?

Doug

**Comment by dvigneshwer** [comment]
Thanks I was enquring about the functions only
