### ISSUE TITLE
OpenCV Error: Assertion failed on demo.py

### ISSUE THREAD

**Issue by emavgl** [dougsouza/face-frontalization#11]
Hi, I have just downloaded the code and installed all the dependencies. Then, I've run demo.py. But I got the error below. Do you have any suggestion?

> Number of faces detected: 1
('query image shape:', (250, 250, 3))
OpenCV Error: Assertion failed (dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX) in remap, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 4956
Traceback (most recent call last):
  File "demo.py", line 49, in <module>
    demo()
  File "demo.py", line 38, in demo
    frontal_raw, frontal_sym = frontalize.frontalize(img, proj_matrix, model3D.ref_U, eyemask)
  File "/home/emanuele/Desktop/test_hiding/face-frontalization-master/frontalize.py", line 57, in frontalize
    frontal_raw[ind_frontal, :] = cv2.remap(img, temp_proj2[0, :].astype('float32'), temp_proj2[1, :].astype('float32'), cv2.INTER_CUBIC)
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:4956: error: (-215) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function remap

I'm using OpenCV '3.2.0'

**Comment by dougsouza** [comment]
Hi @emavgl,

This is probably because of your OpenCV version. I tested with only version 3.0, the remap function probably have changed. You can either see the OpenCV 3.2 docs and fix the code to use the function correctly or install OpenCV 3.0.0.

I am going to fix the readme where I specify "OpenCV Python Wraper >= 3.0.0". Sorry for this inconvenience.

**Comment by allenlyj** [comment]
@emavgl 
I met this problem two. Have you by any chance fixed the problem? I tried to look into the documentation but I don't think the API has been changed. 
@dougsouza 
I have to use opencv 3.2 for some reason. Can you provide any clue regarding how to fix this issue? Your help is greatly appreciated.

**Comment by allenlyj** [comment]
@emavgl @dougsouza 
Guys, I found a solution. Tried to recompile the OpenCV 3.2 with the specific line commented out, and then it worked all good. Hope this information can be helpful.

**Comment by rxb3753** [comment]
@allenlyj 
Can you please help me by telling what lines you commented and recompiled OpenCV 3.2?
Need your help **ASAP.**  It would be great if you could explain the steps to recompile OpenCV 3.2
Thanks in Advance.

**Comment by allenlyj** [comment]
@rxb3753 
To make things easier I downloaded a clean new version of the OpenCV source code. Go to <your path to opencv>/opencv/modules/imgproc/src/imgwarp.cpp, comment out line 4956:
CV_Assert( dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX );

Then just follow the standard procedure to compile the OpenCV binary, and install it again. The new install should cover the old one, and you should be all good,

**Comment by xiaoyun4** [comment]
It works fine with version 3.1.0.5

**Comment by jtressle** [comment]
Had the same issue and was able to fix issue correctly (instead of just recompiling).  Easy to figure out by understanding the opencv error.  Error states src and dst matrices can't have row or col greater than about 32000.  Demo currently does remap on a ~90K length matrix.  This was probably allowed in older version of Opencv.  To fix, the remap matrices should be [320 x 320].  

I went ahead and rewrote frontalize.py to work with OpenCV 3.2.  My code is attached.  It works on the demo, but could have some other issues.

[frontalize.py.txt](https://github.com/dougsouza/face-frontalization/files/1403791/frontalize.py.txt) 

Thanks again  @dougsouza for great software!

**Comment by TalHassner** [comment]
FYI, there is a [followup project ](https://github.com/fengju514/Face-Pose-Net) which may resolve some of these issues.

**Comment by joseph-zhong** [comment]
@jtressle Thanks for the update! I just checked and it made `demo.py` work for OpenCV 3.4, I'll check for larger images soon...

Just a quick question @TalHassner, since it seems many people are running into this, how long do you think it'd be to merge this as a pull request?

Thanks!

**Comment by dougsouza** [comment]
@joseph-zhong, just send a PR and I will test and merge it.

Cheers

**Comment by dougsouza** [comment]
@joseph-zhong, it's merged, thanks! Reopen if needed.

Cheers

**Comment by ghost** [comment]
I am still facing issues with using large images. Can anyone please help me, it's urgent for me.

**Comment by ibaris** [comment]
I face the same issue. Every issue related to this Bug is closed but the issue still exists up to now. I mean I know that remapping uses short, integer arithmetic's in order to increase the performance. But sometimes performance is negligible if the function does not work. 

I solved the problem by chunking my output data and the inputted pixel x and y values.
