### ISSUE TITLE
how to extract the frontalized portion only?

### ISSUE THREAD

**Issue by dvigneshwer** [dougsouza/face-frontalization#4]
I have just started going through the code, could you help me in which part should I start looking for in order to extract the face frontalized crop.

The crop before merging with the original image.

**Comment by dougsouza** [comment]
This is a good question. What I do to crop the frontalized face only is detect the face again after it was frontalized, then crop the area of the detection. In code this would be something like:

```
import dlib

detector = dlib.get_frontal_face_detector()
# Assuming you already have a frontalized face called frontalized_face
dets = detector(frontalized_face, 1)
# BE AWARE IF THERE IS MORE THAN ONE FACE IN THE IMAGE
d = dets[0]
cropped_face = frontalized_face[d.left():d.right(), d.top():d.bottom(), :]
```

**Comment by dvigneshwer** [comment]
Thanks @dougsouza, have tried this and works well and some part of the back ground comes in to the crop.
But I was wondering if its possible only to detect the 3D crop which has been frontalized from the code?

**Comment by dougsouza** [comment]
@dvigneshwer, in this case I think you could use the coordinates of the most outlying landmarks to crop accordingly. The problem is that you would have to detect the landmarks again after frontalizing, which would slow your code a little. That is the one solution I can think of right now, maybe it is possible to change the frontalization function to crop right after frontalizing but that would require some effort to implement. If you find out how to do it I will be happy to accept a PR :)

**Comment by dvigneshwer** [comment]
Thanks @dougsouza, Have tried the first method found the extreme landmark points and saved the crop from the frontalized image. It has similar results to that of face detector. 
Will update in case if I manage to get face frontal crop.
